const DocApi = [
    {
      image: "/pics/doc.jpg",
      doctorName: "Dr. Arun Sharma",
      doctorId: "D1001",
      speciality: "Cardiology",
      bio: "Highly experienced cardiologist specializing in interventional cardiology and heart failure.",
      qualification: "MBBS, MD (Cardiology), DM (Cardiology)",
      yearsOfExperience: 20,
      languageSpoken: ["English", "Hindi"],
      feeStructure: "Consultation: ₹1500, Procedures: Varies",
      acceptedPaymentMethod: ["Cash", "Credit Card", "UPI"],
      pastExperience: "Apollo Hospitals, Fortis Escorts Heart Institute",
      awardsAndRecognitions: ["Best Cardiologist Award", "Fellow of the Indian College of Cardiology"],
      publishedResearchAndArticles: ["Several publications in international cardiology journals"],
      treatmentOffered: ["Angioplasty", "Pacemaker Implantation", "Heart Failure Management"],
      contactInformation: {
        phoneNumber: "+919876543210",
        email: "arun.sharma@example.com",
      },
      clinicHospitalAddress: "12, MG Road, Bangalore, Karnataka",
      operatingHours: "Mon-Sat: 10:00 AM - 6:00 PM",
      appointmentAvailability: "Available on weekdays, prior appointment required",
      averageRating: 4.8,
      welcomeMessage: "Welcome to my clinic. Providing comprehensive cardiac care.",
      socialMediaProfiles: {
        linkedin: "linkedin.com/in/arunsharma",
        twitter: "twitter.com/arunsharma",
      },
    },
    {
      image: "/pics/doc.jpg",
      doctorName: "Dr. Priya Desai",
      doctorId: "D1002",
      speciality: "Dermatology",
      bio: "Expert dermatologist with a focus on cosmetic dermatology and skin diseases.",
      qualification: "MBBS, MD (Dermatology)",
      yearsOfExperience: 15,
      languageSpoken: ["English", "Gujarati"],
      feeStructure: "Consultation: ₹1000, Treatments: Varies",
      acceptedPaymentMethod: ["Cash", "Credit Card"],
      pastExperience: "Lilavati Hospital, Kaya Skin Clinic",
      awardsAndRecognitions: ["Young Dermatologist Award", "Member of the Indian Association of Dermatologists"],
      publishedResearchAndArticles: ["Articles on skin aging and laser treatments"],
      treatmentOffered: ["Laser Hair Removal", "Acne Treatment", "Skin Rejuvenation"],
      contactInformation: {
        phoneNumber: "+919988776655",
        email: "priya.desai@example.com",
      },
      clinicHospitalAddress: "45, Linking Road, Mumbai, Maharashtra",
      operatingHours: "Tue-Sun: 11:00 AM - 7:00 PM",
      appointmentAvailability: "Appointments available on all days except Monday",
      averageRating: 4.6,
      welcomeMessage: "Your skin's health is my priority. Contact me for expert care.",
      socialMediaProfiles: {
        instagram: "instagram.com/priyadesai_derm",
      },
    },
    {
      image: "/pics/doc.jpg",
      doctorName: "Dr. Rajesh Kumar",
      doctorId: "D1003",
      speciality: "Orthopedics",
      bio: "Experienced orthopedic surgeon specializing in joint replacements and sports injuries.",
      qualification: "MBBS, MS (Orthopedics), DNB (Orthopedics)",
      yearsOfExperience: 18,
      languageSpoken: ["English", "Hindi", "Punjabi"],
      feeStructure: "Consultation: ₹1200, Surgeries: Varies",
      acceptedPaymentMethod: ["Cash", "Credit Card", "Insurance"],
      pastExperience: "AIIMS, Max Super Speciality Hospital",
      awardsAndRecognitions: ["Best Orthopedic Surgeon", "Fellow of the Indian Orthopedic Association"],
      publishedResearchAndArticles: ["Research on minimally invasive joint surgeries"],
      treatmentOffered: ["Knee Replacement", "Arthroscopy", "Fracture Treatment"],
      contactInformation: {
        phoneNumber: "+919765432109",
        email: "rajesh.kumar@example.com",
      },
      clinicHospitalAddress: "78, Sector 17, Chandigarh, Punjab",
      operatingHours: "Mon-Fri: 9:00 AM - 5:00 PM",
      appointmentAvailability: "Limited appointments, booking required",
      averageRating: 4.7,
      welcomeMessage: "Specialized orthopedic care for a better quality of life.",
      socialMediaProfiles: {
        facebook: "facebook.com/rajeshkumar.ortho",
      },
    },
    {
      image: "/pics/doc.jpg",
      doctorName: "Dr. Meena Patel",
      doctorId: "D1004",
      speciality: "Gynecology",
      bio: "Dedicated gynecologist providing comprehensive women's health services.",
      qualification: "MBBS, MD (Gynecology)",
      yearsOfExperience: 12,
      languageSpoken: ["English", "Hindi", "Marathi"],
      feeStructure: "Consultation: ₹900, Procedures: Varies",
      acceptedPaymentMethod: ["Cash", "Credit Card", "UPI"],
      pastExperience: "KEM Hospital, Cloudnine Hospitals",
      awardsAndRecognitions: ["Women's Health Champion", "Member of the Federation of Obstetric and Gynecological Societies of India"],
      publishedResearchAndArticles: ["Articles on women's reproductive health"],
      treatmentOffered: ["Prenatal Care", "Infertility Treatment", "Menopause Management"],
      contactInformation: {
        phoneNumber: "+919898989898",
        email: "meena.patel@example.com",
      },
      clinicHospitalAddress: "22, Baner Road, Pune, Maharashtra",
      operatingHours: "Mon-Sat: 10:00 AM - 7:00 PM",
      appointmentAvailability: "Flexible appointments available",
      averageRating: 4.9,
      welcomeMessage: "Empowering women with expert gynecological care.",
      socialMediaProfiles: {},
    },
  ];
  
  export default DocApi;