const doctorReviews = [
    {
      id: 1,
      doctorId: 'D123', 
      patientId: 'P456', 
      patientName: 'Alice Johnson',
      rating: 5, 
      comment: 'Dr. Smith was incredibly professional and attentive. He explained everything clearly, and I felt very comfortable throughout the appointment. Highly recommended!',
      date: '2023-10-26',
      service: 'General Consultation',
      helpful: true,
      responseTime: 'Very Fast', 
      staffRating: 5, 
      facilityRating: 4, 
    },
    {
      id: 2,
      doctorId: 'D456',
      patientId: 'P789',
      patientName: 'Bob Williams',
      rating: 4,
      comment: 'Dr. Lee was knowledgeable, but the wait time was a bit long. The staff was friendly, and the facility was clean.',
      date: '2023-10-25',
      service: 'Dermatology',
      helpful: true,
      responseTime: 'Moderate',
      staffRating: 5,
      facilityRating: 5,
    },
    {
      id: 3,
      doctorId: 'D123',
      patientId: 'P101',
      patientName: 'Charlie Brown',
      rating: 3,
      comment: 'Dr. Smith was okay, but I felt a bit rushed. The explanation of my condition could have been more detailed.',
      date: '2023-10-24',
      service: 'General Consultation',
      helpful: false,
      responseTime: 'Fast',
      staffRating: 4,
      facilityRating: 4,
    },
    {
      id: 4,
      doctorId: 'D789',
      patientId: 'P112',
      patientName: 'Diana Miller',
      rating: 5,
      comment: 'Dr. Garcia is a fantastic cardiologist. She listened carefully to my concerns and provided excellent care. The clinic is also well-maintained.',
      date: '2023-10-23',
      service: 'Cardiology',
      helpful: true,
      responseTime: 'Very Fast',
      staffRating: 5,
      facilityRating: 5,
    },
      {
      id: 5,
      doctorId: 'D456',
      patientId: 'P113',
      patientName: 'Eve Davis',
      rating: 2,
      comment: 'Dr. Lee was not helpful. I felt like my concerns were dismissed. The wait was long, and the staff was unhelpful.',
      date: '2023-10-22',
      service: 'Dermatology',
      helpful: false,
      responseTime: 'Slow',
      staffRating: 1,
      facilityRating: 3,
    },
      {
      id: 6,
      doctorId: 'D101',
      patientId: 'P114',
      patientName: 'Frank Wilson',
      rating: 4,
      comment: 'Dr. Patel was very kind and professional. The appointment was quick and efficient. The facility was very clean.',
      date: '2023-10-21',
      service: 'Pediatrics',
      helpful: true,
      responseTime: 'Fast',
      staffRating: 5,
      facilityRating: 5,
    }
  ];
  
  export default doctorReviews;